---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/All-Emo-e-Rmo-Sigr-Pne-Colmo-Il-Sig-r-Cardinale-Al"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/readux:thgg7_00000001.jp2/full/full/0/default.jpg
image_size:
  page:
    width: 9061
    height: 13088
permalink: pretty
publication_info:
  title: All'Emo., e Rmo. Sigr. Pne. Colmo., Il Sig.r Cardinale Alessandro Albani
    Emo., e Rmo. pri
  date: '2021'
  editors: []
show_annotation_author: true
source_info:
  title: All'Emo., e Rmo. Sigr. Pne. Colmo., Il Sig.r Cardinale Alessandro Albani
    Emo., e Rmo. pri
  via_readux: true
tagline: an annotated digital edition
title: All'Emo., e Rmo. Sigr. Pne. Colmo., Il Sig.r Cardinale Alessandro Albani Emo.,
  e Rmo. pri
url: https://jayvarner.github.io
version: 0.7
